### ISSUE TITLE
Publishing QmlLive workspace to remote device ignores some subdirectories

### ISSUE THREAD

**Issue by Karry** [sailfishos/qmllive#6]
Hi. 

I have following directory structure in my project (harbour-osmscout):
```
/poi-icons
/qml/custom
/qml/pages
```
This corresponds with the structure on the device/package in the directory `/usr/share/harbour-osmscout/`. When I start application with `qmlliveruntime-sailfish` wrapper on the device and open qmllivebech on the desktop, it synchronize just changes in qml directory, but not in `qml/pages` nor `qml/custom`...

To verify it, I disabled overlay and use writable directory for the workspace:
```
qmlliveruntime-sailfish  \
  --allow-create-missing \
  --no-updates-as-overlay \
  --workspace /home/nemo/harbour-osmscout-qmllive \
  /usr/bin/harbour-osmscout
```

After publishing workspace from QmlLiveBench, workspace on the device looks like this:
```
[root@Sailfish ~]# find /home/nemo/harbour-osmscout-qmllive/ -name *.qml
/home/nemo/harbour-osmscout-qmllive/qml/main.qml
/home/nemo/harbour-osmscout-qmllive/qml/l10n.qml
/home/nemo/harbour-osmscout-qmllive/qml/AboutDialog.qml
/home/nemo/harbour-osmscout-qmllive/qml/desktop.qml
/home/nemo/harbour-osmscout-qmllive/qml/SpeedIndicator.qml
/home/nemo/harbour-osmscout-qmllive/qml/SearchDialog.qml
```
Qml files from `custom` and `pages` subdirectories  are missing...

**Comment by martyone** [comment]
I cannot reproduce that. (I tried with osmscout-sailfish sources as the workspace, using the same qmlliveruntime-sailfish command line as you except that I used /usr/bin/calqlatr executable from the calqlatr example instead of /usr/bin/harbour-osmscout which I didn't build)

**Comment by Karry** [comment]
Sorry, I dont write whole true to this issue. When I open project root as qmlitvebench workspace, it is complaining about huge number of files: 

> Unable to monitor file changes: The configured limit of 100 directories was exceeded. 

To avoid this message and handle the fact that installed paths are slightly different from git structure, I prepared workspace (on PC) as separate directory and create symbolic links to `qml` and `poi-icons`...

```
karry@LatitudeMachine:~/SailfishOS/projects/osmscout-sailfish/qmllive-workspace$ ls -l
total 0
lrwxrwxrwx 1 karry karry 13 dub  8 07:41 poi-icons -> ../icons/poi/
lrwxrwxrwx 1 karry karry  6 dub  8 07:40 qml -> ../qml
```
With this workspace it don't synchronise qml/pages and qml/custom directories... But when I prepare workspace this way:
```
karry@LatitudeMachine:~/SailfishOS/projects/osmscout-sailfish/qmllive-workspace$ ln -s ../icons/poi/ poi-icons
karry@LatitudeMachine:~/SailfishOS/projects/osmscout-sailfish/qmllive-workspace$ mkdir qml
karry@LatitudeMachine:~/SailfishOS/projects/osmscout-sailfish/qmllive-workspace$ cd qml/
karry@LatitudeMachine:~/SailfishOS/projects/osmscout-sailfish/qmllive-workspace/qml$ ln -s ../../qml/main.qml .          
karry@LatitudeMachine:~/SailfishOS/projects/osmscout-sailfish/qmllive-workspace/qml$ ln -s ../../qml/custom . 
karry@LatitudeMachine:~/SailfishOS/projects/osmscout-sailfish/qmllive-workspace/qml$ ln -s ../../qml/pages .  
```
It works fine... So problem is somehow with following symbolic links...?

**Comment by martyone** [comment]
> So problem is somehow with following symbolic links...?

That's likely to be the case. Consider using the `--maxdirwatch` option to increase the max number of directories to watch. If this causes other troubles, we can try to fix it better on bench side.
